java.compatibility=17
kotlin.compatibility=2.0.0

kdoc.olderVersions=
kdoc.projects=:openfeedback,:openfeedback-m3,:openfeedback-resources,:openfeedback-ui-models,:openfeedback-viewmodel
kdoc.artifactId=kdoc

pom.groupId=io.openfeedback
pom.version=1.0.0-alpha.5-SNAPSHOT
pom.description=openfeedback-sdk-kotlin
pom.vcsUrl=https://github.com/paug/openfeedback-sdk-kotlin
pom.developer=openfeedback-sdk-kotlin authors
pom.license=MIT License

# https://github.com/GradleUp/tapmoc/issues/82
checkDependenciesCompatibility=false